output   = "models"
wipe     = true
no-tests = true

[psql]
  dbname = "booking"
  host   = "localhost"
  port   = 5433
  user   = "postgresb"
  pass   = "Phong0832210125"
  schema = "public"
  sslmode = "disable"